
language: python
python:
  - "2.7"
  - "3.6"
sudo: required
cache: pip
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-6.0
    - rabbitmq-server
    - jq
    - curl

services:
  - docker

git:
  submodules: false

# This script is triggered only with python2.7 (as below python3.6 is excluded from the matrix)
before_install:
  - sudo apt update && sudo apt install -y protobuf-compiler
  - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
  - git submodule update --init --recursive

before_script:
  - pip install -r source/tyr/requirements_dev.txt
  - bash source/scripts/build_protobuf.sh

script:
  - bash source/scripts/check_submodules.sh
  - pushd source/tyr && PYTHONPATH=.:../navitiacommon/ py.test --doctest-modules --ignore=migrations/ && popd

matrix:
  include:  # This script is triggered only with python3.6
    - python: "3.6"
      before_script:
        - pip install -r requirements_pre-commit.txt
        - pre-commit install
        - bash source/scripts/build_protobuf.sh
      script:
        - pre-commit run --all --show-diff-on-failure
        - ./source/scripts/checkJenkinsJob.sh Artemis
        - ./source/scripts/checkJenkinsJob.sh Artemis_idfm

    - language: "cpp"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang-6.0
          - clang-tidy-6.0
          - cmake
          - libzmq3-dev
          - liblog4cplus-dev
          - libgoogle-perftools-dev
          - libprotobuf-dev
          - libpqxx-dev
          - libboost-chrono-dev
          - libboost-date-time-dev
          - libboost-filesystem-dev
          - libboost-iostreams-dev
          - libboost-program-options-dev
          - libboost-regex-dev
          - libboost-serialization-dev
          - libboost-system-dev
          - libboost-test-dev
          - libboost-thread-dev
          - libproj-dev
          - libgeos-dev
          - libosmpbf-dev
      before_script:
        - mkdir build && pushd build && cmake ../source -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && make protobuf_files && popd
      script:
        - ./scripts/run_clang_tidy_on_diff.sh -r origin -s /home/travis -b /home/travis/build

  exclude:
    - python: "3.6"
